version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - ${HTTP_PORT}
      - '9000'
    volumes:
      - app_data:/var/www/html
    environment:
      - HTTP_PORT=80
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
      - HTTP_PORT=80
      - HTTPS_PORT=443
    expose:
      - ${HTTP_PORT}
      - ${HTTPS_PORT}
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
